# Site settings

# NB! Set your site's url, otherwise nothing will work
url: ""

# Google tracking id (optional)
google-tracking-id: ""

#############
# HTML Head #
#############

lang: "ko"
author: "Dev_Ilsan"
title: "{ 개발일산 }"
description: "개발일산의 블로그입니다."
keywords: "developer, portfolio, blog, jekyll"
favicon: "/img/favicon.ico"

################
# Header layout#
################
black-favicon: "/img/black-lab-glass.ico"
background-img: "intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

quote: "안녕하세요! 고양시 일산에서 개발하는 개발일산입니다."
me-img: "/img/jetpacktocat.png"

#######
# Blog #
########

post-preview-words: 96
paginate: 5
email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: ""

############
# Timeline #
############

events:
  - image: "/img/timeline/spidertocat.png"
    date: "2024 - 현재"
    description: "현재 진행 중인 프로젝트"
  - image: "/img/timeline/baracktocat.jpg"
    date: "2023 - 2024"
    description: "개발 공부 시작"

# First image of the Timeline
timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "your@email.com"

################
# Author Blurb #
################

author_blurb_image: "/img/author.png"
author_blurb: "AI를 통한 자동화 개발에 관심이 많은 사람입니다. 새로운 기술을 배우고 적용하는 것을 좋아합니다."

##################
# Social Buttons #
##################

social:
  - icon: "github"
    url: "https://github.com/phd-peter"
  - icon: "linkedin-in"
    url: "https://www.linkedin.com/in/yourusername"
  - icon: "x-twitter"
    url: "https://twitter.com/yourusername"

# Sections shown in the index page
pages_list:
  About: "about"
  Blog: "latest-post"
  Timeline: "timeline"
  Contact: "contact"

# Exclusion list from the generated _site
exclude:
  - LICENSE
  - README.md
  - CONTRIBUTING
  - CONTRIBUTORS
  - scripts
  - Dockerfile
  - docker-compose.yml
  - temp-theme/

# Pagination path
paginate_path: "blog/page:num/"

# Enable minification SASS
sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-spaceship